# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firetest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Firetest

  target 'FiretestTests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Messaging'

end
